# Generated by Django 3.1.4 on 2021-02-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_transaccion_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='numero',
        ),
    ]
